name: Fetch Supported Assets for Alternative Datasets

on:
  schedule:
    - cron:  "0 10 * * 1" # Runs "at 10 UTC every Monday" (see https://crontab.guru)
  workflow_dispatch:  # Run on manual trigger
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        
      - name: Fetch Supported Assets of Alt Datasets from nas
        run: python code-generators/alt-dataset-supported-assets-generator.py
      
      - name: Commit and Push
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit --allow-empty -m "Code Generation from code generators"
          git push
