name: Run Code Generators

on:
  schedule:
    - cron:  "0 10 * * 1" # Runs "at 10 UTC every Monday" (see https://crontab.guru)
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.22.3
      - name: Run API Reference Code Generator Python Script
        run: python code-generators/docs-generatorAPI-Reference-Code-Generator.py
      - name: Run Writing Algorithm API Code Generator Python Script
        run: python code-generators/docs-generatorWriting-Algorithm-API-Code-Generator.py
      - name: Run Alternative Datasets Code Generator Python Script
        run: python code-generators/docs-generatorAlternative-Datasets-Code-Generator.py
      - name: Run Fundamentals Table Code Generator Python Script
        run: python code-generators/docs-generatorfundamentals-table-code-generator.py
      - name: Run Future Table Code Generator Python Script
        run: python code-generators/docs-generatorfuture-table-code-generator.py
      - name: Run Supported Assets Table Code Generator Python Script
        run: python code-generators/docs-generatorSupported-Assets-Table-Code-Generator.py
      - name: Run Indicator Reference Code Generator Python Script
        run: python code-generators/docs-generatorIndicator-Reference-Code-Generator.py
      - name: Run Fred Categories Table Code Generator Python Script
        run: python code-generators/docs-generatorfred-categories-table-code-generator.py
      - name: Run US Energy Categories Table Code Generator Python Script
        run: python code-generators/docs-generatorus-energy-indicators-code-generator.py
      - name: Run OrderError Table Code Generator Python Script
        run: python code-generators/docs-generatororder-error-code-generator.py
      - name: Run Market Hour Reference Code Generator Python Script
        run: python code-generators/docs-generatormarket-hour-code-generator.py
      - name: Run Market Hour Convertor Python Script
        run: python code-generators/docs-generatormarket-hour-convertor.py
      - name: Run Securities Objects Table Code Generator Python Script
        run: python code-generators/docs-generatorsecurity-portfolio-table-generator.py
      - name: Commit and Push
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit --allow-empty -m "Updates API References"
          git push
