name: Run Code Generators

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Our Platform and Alpha Stream API
        run: python API-Reference-Code-Generator.py

