name: Run Code Generators

on:
  schedule:
    - cron:  "0 10 * * 1" # Runs "at 10 UTC every Monday" (see https://crontab.guru)
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.22.3
      - name: Run API Reference Code Generator Python Script
        run: python code-generators/docs-generator/API-Reference-Code-Generator.py
      - name: Run Writing Algorithm API Code Generator Python Script
        run: python code-generators/docs-generator/Writing-Algorithm-API-Code-Generator.py
      - name: Run Alternative Datasets Code Generator Python Script
        run: python code-generators/docs-generator/Alternative-Datasets-Code-Generator.py
      - name: Run Fundamentals Table Code Generator Python Script
        run: python code-generators/docs-generator/fundamentals-table-code-generator.py
      - name: Run Future Table Code Generator Python Script
        run: python code-generators/docs-generator/future-table-code-generator.py
      - name: Run Supported Assets Table Code Generator Python Script
        run: python code-generators/docs-generator/Supported-Assets-Table-Code-Generator.py
      - name: Run Indicator Reference Code Generator Python Script
        run: python code-generators/docs-generator/Indicator-Reference-Code-Generator.py
      - name: Run Fred Categories Table Code Generator Python Script
        run: python code-generators/docs-generator/fred-categories-table-code-generator.py
      - name: Run US Energy Categories Table Code Generator Python Script
        run: python code-generators/docs-generator/us-energy-indicators-code-generator.py
      - name: Run Market Hour Reference Code Generator Python Script
        run: python code-generators/docs-generator/market-hour-code-generator.py
      - name: Run Market Hour Convertor Python Script
        run: python code-generators/docs-generator/market-hour-convertor.py
      - name: Run Securities Objects Table Code Generator Python Script
        run: python code-generators/docs-generator/security-portfolio-table-generator.py
      - name: Run Enum Table Code Generator Python Script
        run: python code-generators/docs-generator/enum-table-generator.py
      - name: Commit and Push
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit --allow-empty -m "Updates API References"
          git push
