name: Single-HTML-Page Documentation Generation

on:
  schedule:
    - cron:  "0 12 * * *" # Runs "at 10 UTC every Monday" (see https://crontab.guru)
  workflow_dispatch:  # Run on manual trigger

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          pip install beautifulsoup4==4.12.2
          pip install pdfkit==1.0.0
          sudo apt-get install wkhtmltopdf

      - name: Run Single-HTML-Page Documentation Generator
        run: python SinglePageDocGenerator.py