name: Update Python API Reference

on:
  schedule:
    - cron: "0 23 * * 5" # Runs at 23:00 UTC every Friday
  workflow_dispatch:  # Run on manual trigger

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Free space
        run: df -h && rm -rf /opt/hostedtoolcache* && df -h

      - name: Install dependencies (pip)
        run: |
          python -m pip install --upgrade pip
          pip install quantconnect-stubs

      - name: Run the Python API Reference Generator
        run: cd code-generators && python main.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-west-1

      - name: Copy files to the S3 website content bucket
        run: aws s3 cp ./site s3://${{ secrets.AWS_BUCKET }}/python-api-reference
