name: Update Python API Reference

on:
  schedule:
    - cron: "0 23 * * 5" # Runs at 23:00 UTC every Friday
  workflow_dispatch:  # Run on manual trigger

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Free space
        run: df -h && rm -rf /opt/hostedtoolcache* && df -h

      - name: Install dependencies (pip)
        run: |
          python -m pip install --upgrade pip
          pip install quantconnect-stubs mkdocs mkdocs-material "mkdocstrings[python]" black

      - name: Run the Python API Reference Generator
        working-directory: code-generators/python_api_reference
        run: python main.py

      - name: Build site with MkDocs
        working-directory: code-generators/python_api_reference
        run: mkdocs build --clean

      - name: Zip site
        working-directory: code-generators/python_api_reference/site
        run: zip -r -s 45m "$GITHUB_WORKSPACE/Resources/python-api-reference/site.zip" .

      - name: Push ZIP to branch
        run: |
          BRANCH=github-action-python-api-reference
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

          # Create branch (or switch if it exists)
          git checkout -b "$BRANCH" || git checkout "$BRANCH"

          # Add only the zip at the requested path inside the repo
          git add -f Resources/python-api-reference/site.z*

          # If nothing changed, exit quietly
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Update python-api-reference.zip"
          git push --set-upstream origin "$BRANCH" -f
