name: Check Documentation for Broken Links

on:
  schedule:
    - cron:  "0 10 * * 1-5" # Runs at 10:00 UTC on Mon, Tue, Wed, Thu and Fri. (see https://crontab.guru)
  workflow_dispatch:  # Run on manual trigger
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Build and run the url tester csproj
        run: |
          cd "URL Test"
          dotnet build /p:Configuration=Release /v:quiet /p:WarningLevel=1 URLTest.csproj
          dotnet run bin/Debug/net6.0/process.dll
