name: Validate brokerage and data provider YAML

on:
  workflow_dispatch:      # Runs on manual trigger
    
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Validate YAML
        run: python validate_brokerage_and_data_provider_yaml.py
