name: Run All Code Generators

on:
  schedule:
    - cron:  "0 10 * * 1" # Runs "at 10 UTC every Monday" (see https://crontab.guru)
  workflow_dispatch:  # Run on manual trigger

jobs:
  org-api-ref:
    uses: ./.github/workflows/workflow_baseCodeGen.yml
    with:
      script-name: API-Reference-Code-Generator
    secrets: inherit

  wa-api-ref:
    uses: ./.github/workflows/workflow_baseCodeGen.yml
    with:
      script-name: Writing-Algorithm-API-Ref-Code-Generator
    secrets: inherit