name: Run All Code Generators

on:
  workflow_dispatch:  # Run on manual trigger
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python code-generators/get-supported-libraries.py